version: "3.9"

services:
  backend:
    build:
      context: ./elearning-backend   # correct folder
      dockerfile: Dockerfile
    ports:
      - "5731:5731"
    volumes:
      - ./elearning-backend/uploads:/app/uploads
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend           # correct folder
      dockerfile: Dockerfile
    ports:
      - "80:80"
