services:
  backend:
    build:
      context: ./elearning-backend    # backend folder
      dockerfile: Dockerfile
    ports:
      - "5731:5731"
    volumes:
      - ./elearning-backend/uploads:/app/uploads
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend             # frontend folder
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
